apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-operators-project.yaml
  - mariadb-operator.yaml
  - postgres-operator.yaml
  - rabbitmq-operator.yaml
  - messaging-topology-operator.yaml
  - ingress-nginx.yaml
