---

# we don't want to enable OpenStack Helm's
# helm.sh/hooks because they set them as
# post-install,post-upgrade which in ArgoCD
# maps to PostSync. However the deployments
# and statefulsets in OpenStack Helm
# depend on the jobs to complete, which they
# can't if they set to deploy in PostSync
helm3_hook: false

bootstrap:
  image:
    enabled: false
    openstack:
      enabled: false
  network:
    enabled: false
    openstack:
      enabled: false
  object_store:
    enabled: false
    openstack:
      enabled: false

conf:
  ironic:
    conductor:
      automated_clean: false
    dhcp:
      dhcp_provider: dnsmasq
    oslo_messaging_rabbit:
      rabbit_ha_queues: true

endpoints:
  oslo_messaging:
    namespace: null
    statefulset:
      replicas: 3
      name: rabbitmq-server
    hosts:
      default: rabbitmq-nodes

network:
  api:
    ingress:
      public: true
      classes:
        namespace: "nginx"
        cluster: "nginx-openstack"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    external_policy_local: false
    node_port:
      enabled: false
  pxe:
    device: ens1f0

  # configure OpenStack Helm to use Undercloud's ingress
  # instead of expecting the ingress controller provided
  # by OpenStack Helm
  use_external_ingress_controller: true

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs: null
  static:
    api:
      jobs:
        - ironic-db-sync
        - ironic-ks-user
        - ironic-ks-endpoints
      services:
        - endpoint: internal
          service: oslo_db
        - endpoint: internal
          service: oslo_messaging
    conductor:
      jobs:
        - ironic-db-sync
        - ironic-ks-user
        - ironic-ks-endpoints
      services:
        - endpoint: internal
          service: oslo_db
        - endpoint: internal
          service: oslo_messaging
    # (nicholas.kuechler) The upstream helm values have ironic-db-init
    # as a dependency for db_sync, but we have job_db_init false so
    # ironic-db-init never gets created, and this dependency won't pass.
    # unset it, so that ironic-db-init is no longer listed in it.
    # https://opendev.org/openstack/openstack-helm/src/branch/master/ironic/values.yaml#L310-L312
    db_sync:
      jobs:

manifests:
  job_db_init: false
  job_db_drop: false
  job_manage_cleaning_network: false
  job_rabbit_init: false
  secret_db: false
  secret_rabbitmq: false
  secret_registry: false
