---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ironic-mariadb-db.yaml
  - ironic-rabbitmq-queue.yaml
  - dnsmasq-pvc.yaml
  - dnsmasq-cm.yaml
  - dnsmasq-ss.yaml

helmGlobals:
  chartHome: ../../charts/
helmCharts:
  - name: ironic
    namespace: openstack
    releaseName: ironic
    repo: https://tarballs.opendev.org/openstack/openstack-helm/
    version: 0.2.10
    valuesFile: aio-values.yaml
    additionalValuesFiles:
    - ../openstack-2023.1-jammy.yaml
    - ../../secret-openstack.yaml
